package com.fuhui.mybatis.generator.dao;

import com.fuhui.mybatis.generator.model.Platform;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface PlatformMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbggenerated Thu Dec 07 16:23:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbggenerated Thu Dec 07 16:23:38 CST 2017
     */
    int insert(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbggenerated Thu Dec 07 16:23:38 CST 2017
     */
    int insertSelective(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbggenerated Thu Dec 07 16:23:38 CST 2017
     */
    Platform selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbggenerated Thu Dec 07 16:23:38 CST 2017
     */
    int updateByPrimaryKeySelective(Platform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbggenerated Thu Dec 07 16:23:38 CST 2017
     */
    int updateByPrimaryKey(Platform record);

    /**
     * 根据平台的名称查询平台是否已记录
     * @param name
     * @return
     */
    Platform getPlatFormByName(String name);


    /**
     * 获取平台按照展示位置排序的集合
     * @return
     */
    List<Platform> selectAndGetList();
}