package com.fuhui.mybatis.generator.dao;

import com.fuhui.mybatis.generator.model.Fh_Loan_Debt;
public interface Fh_Loan_DebtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int insert(Fh_Loan_Debt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int insertSelective(Fh_Loan_Debt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    Fh_Loan_Debt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int updateByPrimaryKeySelective(Fh_Loan_Debt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int updateByPrimaryKey(Fh_Loan_Debt record);
}