package com.fuhui.mybatis.generator.dao;

import com.fuhui.mybatis.generator.model.Role;
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int deleteByPrimaryKey(Long roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    Role selectByPrimaryKey(Long roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    int updateByPrimaryKey(Role record);
}