package com.fuhui.mybatis.generator.dao;

import com.fuhui.common.entity.QueryCondition;
import com.fuhui.mybatis.generator.model.User_Browsing_History;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface User_Browsing_HistoryMapper {
    /**
     * 获取用户的平台浏览记录
     * @param queryCondition
     * @return
     */
    List<User_Browsing_History> selectUserBrowsingDetailsList(QueryCondition queryCondition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_browsing_history
     *
     * @mbggenerated Fri Dec 08 11:29:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_browsing_history
     *
     * @mbggenerated Fri Dec 08 11:29:09 CST 2017
     */
    int insert(User_Browsing_History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_browsing_history
     *
     * @mbggenerated Fri Dec 08 11:29:09 CST 2017
     */
    int insertSelective(User_Browsing_History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_browsing_history
     *
     * @mbggenerated Fri Dec 08 11:29:09 CST 2017
     */
    User_Browsing_History selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_browsing_history
     *
     * @mbggenerated Fri Dec 08 11:29:09 CST 2017
     */
    int updateByPrimaryKeySelective(User_Browsing_History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_browsing_history
     *
     * @mbggenerated Fri Dec 08 11:29:09 CST 2017
     */
    int updateByPrimaryKey(User_Browsing_History record);
}