package com.fuhui.mybatis.sys.dao;

import com.fuhui.common.entity.QueryCondition;
import com.fuhui.mybatis.sys.model.SysUser;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SysUserMapper {


    /**
     * 获取用户的列表
     * @param queryCondition
     * @return
     */
    List<SysUser> selectFhSysUserList(QueryCondition queryCondition);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Dec 02 16:29:53 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Dec 02 16:29:53 CST 2017
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Dec 02 16:29:53 CST 2017
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Dec 02 16:29:53 CST 2017
     */
    SysUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Dec 02 16:29:53 CST 2017
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Sat Dec 02 16:29:53 CST 2017
     */
    int updateByPrimaryKey(SysUser record);

    /**
     * 查询管理员（单个管理员查询）
     * @author Ren
     * @param sysUser
     * @return
     */
    SysUser selectUser(SysUser sysUser);

    /**
     * 多条件查询管理员（多个管理员查询）
     * TODO 条件后期添加
     * @author Ren
     * @param sysUser
     * @return List<SysUser>
     */
    List<SysUser> selectUsers(SysUser sysUser);

    /**
     * 通过手机号用户管理员的信息
     * @param mobile
     * @return
     */
    SysUser selectByMobile(String mobile);
}