package com.fuhui.mybatis.generator.dao;

import com.fuhui.mybatis.generator.model.PlatformBrowsingHistory;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PlatformBrowsingHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    int insert(PlatformBrowsingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    int insertSelective(PlatformBrowsingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    PlatformBrowsingHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    int updateByPrimaryKeySelective(PlatformBrowsingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    int updateByPrimaryKey(PlatformBrowsingHistory record);

    
    /**
     * 获取用户浏览某个平台的浏览记录
     * @param userid
     * @return
     */
    List<PlatformBrowsingHistory> getInfoByUseridAndplatid(@Param("platid") int platid,@Param("userid") int userid);


    /**
     * 获取用户的历史浏览记录
     * @param userid
     * @return
     */
    List<PlatformBrowsingHistory> getInfoByUserid( int userid);
    /**
     * 获取用户对某平台的浏览记录
     * @param platid
     * @param userid
     * @return
     */
    int getCountInUserAndPlatid(@Param("platid") int platid,@Param("userid") int userid);

    /**
     * 获取用户的浏览记录
     * @param userid
     * @return
     */
    int getCountInUser(int userid);
}