package com.fuhui.mybatis.generator.model;

import java.io.Serializable;
import java.util.Date;

public class Fh_Loan_Debt implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.id
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.title
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.rate
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Long rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.amount
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.loan_push_time
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Integer loanPushTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.loan_push_time_type
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Integer loanPushTimeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.loan_term
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Integer loanTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.loan_apply_condition
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private String loanApplyCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.home_display
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Integer homeDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.loan_need_data
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private String loanNeedData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.url
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.label_display
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Integer labelDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.status
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.list_sort
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Integer listSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fh_loan_debt.date
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.id
     *
     * @return the value of fh_loan_debt.id
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.id
     *
     * @param id the value for fh_loan_debt.id
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.title
     *
     * @return the value of fh_loan_debt.title
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.title
     *
     * @param title the value for fh_loan_debt.title
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.rate
     *
     * @return the value of fh_loan_debt.rate
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Long getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.rate
     *
     * @param rate the value for fh_loan_debt.rate
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setRate(Long rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.amount
     *
     * @return the value of fh_loan_debt.amount
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.amount
     *
     * @param amount the value for fh_loan_debt.amount
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.loan_push_time
     *
     * @return the value of fh_loan_debt.loan_push_time
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Integer getLoanPushTime() {
        return loanPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.loan_push_time
     *
     * @param loanPushTime the value for fh_loan_debt.loan_push_time
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setLoanPushTime(Integer loanPushTime) {
        this.loanPushTime = loanPushTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.loan_push_time_type
     *
     * @return the value of fh_loan_debt.loan_push_time_type
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Integer getLoanPushTimeType() {
        return loanPushTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.loan_push_time_type
     *
     * @param loanPushTimeType the value for fh_loan_debt.loan_push_time_type
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setLoanPushTimeType(Integer loanPushTimeType) {
        this.loanPushTimeType = loanPushTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.loan_term
     *
     * @return the value of fh_loan_debt.loan_term
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Integer getLoanTerm() {
        return loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.loan_term
     *
     * @param loanTerm the value for fh_loan_debt.loan_term
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setLoanTerm(Integer loanTerm) {
        this.loanTerm = loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.loan_apply_condition
     *
     * @return the value of fh_loan_debt.loan_apply_condition
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public String getLoanApplyCondition() {
        return loanApplyCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.loan_apply_condition
     *
     * @param loanApplyCondition the value for fh_loan_debt.loan_apply_condition
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setLoanApplyCondition(String loanApplyCondition) {
        this.loanApplyCondition = loanApplyCondition == null ? null : loanApplyCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.home_display
     *
     * @return the value of fh_loan_debt.home_display
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Integer getHomeDisplay() {
        return homeDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.home_display
     *
     * @param homeDisplay the value for fh_loan_debt.home_display
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setHomeDisplay(Integer homeDisplay) {
        this.homeDisplay = homeDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.loan_need_data
     *
     * @return the value of fh_loan_debt.loan_need_data
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public String getLoanNeedData() {
        return loanNeedData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.loan_need_data
     *
     * @param loanNeedData the value for fh_loan_debt.loan_need_data
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setLoanNeedData(String loanNeedData) {
        this.loanNeedData = loanNeedData == null ? null : loanNeedData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.url
     *
     * @return the value of fh_loan_debt.url
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.url
     *
     * @param url the value for fh_loan_debt.url
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.label_display
     *
     * @return the value of fh_loan_debt.label_display
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Integer getLabelDisplay() {
        return labelDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.label_display
     *
     * @param labelDisplay the value for fh_loan_debt.label_display
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setLabelDisplay(Integer labelDisplay) {
        this.labelDisplay = labelDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.status
     *
     * @return the value of fh_loan_debt.status
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.status
     *
     * @param status the value for fh_loan_debt.status
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.list_sort
     *
     * @return the value of fh_loan_debt.list_sort
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Integer getListSort() {
        return listSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.list_sort
     *
     * @param listSort the value for fh_loan_debt.list_sort
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setListSort(Integer listSort) {
        this.listSort = listSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fh_loan_debt.date
     *
     * @return the value of fh_loan_debt.date
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fh_loan_debt.date
     *
     * @param date the value for fh_loan_debt.date
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Fh_Loan_Debt other = (Fh_Loan_Debt) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getRate() == null ? other.getRate() == null : this.getRate().equals(other.getRate()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getLoanPushTime() == null ? other.getLoanPushTime() == null : this.getLoanPushTime().equals(other.getLoanPushTime()))
            && (this.getLoanPushTimeType() == null ? other.getLoanPushTimeType() == null : this.getLoanPushTimeType().equals(other.getLoanPushTimeType()))
            && (this.getLoanTerm() == null ? other.getLoanTerm() == null : this.getLoanTerm().equals(other.getLoanTerm()))
            && (this.getLoanApplyCondition() == null ? other.getLoanApplyCondition() == null : this.getLoanApplyCondition().equals(other.getLoanApplyCondition()))
            && (this.getHomeDisplay() == null ? other.getHomeDisplay() == null : this.getHomeDisplay().equals(other.getHomeDisplay()))
            && (this.getLoanNeedData() == null ? other.getLoanNeedData() == null : this.getLoanNeedData().equals(other.getLoanNeedData()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getLabelDisplay() == null ? other.getLabelDisplay() == null : this.getLabelDisplay().equals(other.getLabelDisplay()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getListSort() == null ? other.getListSort() == null : this.getListSort().equals(other.getListSort()))
            && (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getRate() == null) ? 0 : getRate().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getLoanPushTime() == null) ? 0 : getLoanPushTime().hashCode());
        result = prime * result + ((getLoanPushTimeType() == null) ? 0 : getLoanPushTimeType().hashCode());
        result = prime * result + ((getLoanTerm() == null) ? 0 : getLoanTerm().hashCode());
        result = prime * result + ((getLoanApplyCondition() == null) ? 0 : getLoanApplyCondition().hashCode());
        result = prime * result + ((getHomeDisplay() == null) ? 0 : getHomeDisplay().hashCode());
        result = prime * result + ((getLoanNeedData() == null) ? 0 : getLoanNeedData().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getLabelDisplay() == null) ? 0 : getLabelDisplay().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getListSort() == null) ? 0 : getListSort().hashCode());
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_loan_debt
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", rate=").append(rate);
        sb.append(", amount=").append(amount);
        sb.append(", loanPushTime=").append(loanPushTime);
        sb.append(", loanPushTimeType=").append(loanPushTimeType);
        sb.append(", loanTerm=").append(loanTerm);
        sb.append(", loanApplyCondition=").append(loanApplyCondition);
        sb.append(", homeDisplay=").append(homeDisplay);
        sb.append(", loanNeedData=").append(loanNeedData);
        sb.append(", url=").append(url);
        sb.append(", labelDisplay=").append(labelDisplay);
        sb.append(", status=").append(status);
        sb.append(", listSort=").append(listSort);
        sb.append(", date=").append(date);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}