package com.fuhui.mybatis.generator.model;

import java.io.Serializable;
import java.util.Date;

public class PlatformBrowsingHistory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_browsing_history.id
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_browsing_history.userid
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_browsing_history.plaid
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    private Integer plaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_browsing_history.planame
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    private String planame;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_browsing_history.desire_money
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    private String desireMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_browsing_history.desire_day
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    private String desireDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_browsing_history.browsing_time
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    private Date browsingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_browsing_history.id
     *
     * @return the value of platform_browsing_history.id
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_browsing_history.id
     *
     * @param id the value for platform_browsing_history.id
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_browsing_history.userid
     *
     * @return the value of platform_browsing_history.userid
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_browsing_history.userid
     *
     * @param userid the value for platform_browsing_history.userid
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_browsing_history.plaid
     *
     * @return the value of platform_browsing_history.plaid
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public Integer getPlaid() {
        return plaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_browsing_history.plaid
     *
     * @param plaid the value for platform_browsing_history.plaid
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public void setPlaid(Integer plaid) {
        this.plaid = plaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_browsing_history.planame
     *
     * @return the value of platform_browsing_history.planame
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public String getPlaname() {
        return planame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_browsing_history.planame
     *
     * @param planame the value for platform_browsing_history.planame
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public void setPlaname(String planame) {
        this.planame = planame == null ? null : planame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_browsing_history.desire_money
     *
     * @return the value of platform_browsing_history.desire_money
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public String getDesireMoney() {
        return desireMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_browsing_history.desire_money
     *
     * @param desireMoney the value for platform_browsing_history.desire_money
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public void setDesireMoney(String desireMoney) {
        this.desireMoney = desireMoney == null ? null : desireMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_browsing_history.desire_day
     *
     * @return the value of platform_browsing_history.desire_day
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public String getDesireDay() {
        return desireDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_browsing_history.desire_day
     *
     * @param desireDay the value for platform_browsing_history.desire_day
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public void setDesireDay(String desireDay) {
        this.desireDay = desireDay == null ? null : desireDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_browsing_history.browsing_time
     *
     * @return the value of platform_browsing_history.browsing_time
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public Date getBrowsingTime() {
        return browsingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_browsing_history.browsing_time
     *
     * @param browsingTime the value for platform_browsing_history.browsing_time
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    public void setBrowsingTime(Date browsingTime) {
        this.browsingTime = browsingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PlatformBrowsingHistory other = (PlatformBrowsingHistory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getPlaid() == null ? other.getPlaid() == null : this.getPlaid().equals(other.getPlaid()))
            && (this.getPlaname() == null ? other.getPlaname() == null : this.getPlaname().equals(other.getPlaname()))
            && (this.getDesireMoney() == null ? other.getDesireMoney() == null : this.getDesireMoney().equals(other.getDesireMoney()))
            && (this.getDesireDay() == null ? other.getDesireDay() == null : this.getDesireDay().equals(other.getDesireDay()))
            && (this.getBrowsingTime() == null ? other.getBrowsingTime() == null : this.getBrowsingTime().equals(other.getBrowsingTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getPlaid() == null) ? 0 : getPlaid().hashCode());
        result = prime * result + ((getPlaname() == null) ? 0 : getPlaname().hashCode());
        result = prime * result + ((getDesireMoney() == null) ? 0 : getDesireMoney().hashCode());
        result = prime * result + ((getDesireDay() == null) ? 0 : getDesireDay().hashCode());
        result = prime * result + ((getBrowsingTime() == null) ? 0 : getBrowsingTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_browsing_history
     *
     * @mbggenerated Tue Dec 12 11:34:34 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", plaid=").append(plaid);
        sb.append(", planame=").append(planame);
        sb.append(", desireMoney=").append(desireMoney);
        sb.append(", desireDay=").append(desireDay);
        sb.append(", browsingTime=").append(browsingTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}