package com.fuhui.mybatis.generator.model;

import java.io.Serializable;
import java.util.Date;

public class Platform implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.id
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.name
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.reference_interest_rate
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String referenceInterestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.reference_day
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String referenceDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.loan_money_low
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String loanMoneyLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.loan_money_high
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String loanMoneyHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.loan_cycle_low
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String loanCycleLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.loan_cycle_high
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String loanCycleHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.fast_loan
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String fastLoan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.fast_loan_time
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String fastLoanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.idcard
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.carrier_warrant
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String carrierWarrant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.bank_card
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String bankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.zhima
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String zhima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.xuexinwang
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String xuexinwang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.taobao
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String taobao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.zhifubao
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String zhifubao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.qq
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.applyconditions
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String applyconditions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.homepage
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String homepage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.displayposition
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private Integer displayposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.onshelves
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String onshelves;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.labelshow
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String labelshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.image_url
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.jumpurl
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private String jumpurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.create_time
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.id
     *
     * @return the value of platform.id
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.id
     *
     * @param id the value for platform.id
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.name
     *
     * @return the value of platform.name
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.name
     *
     * @param name the value for platform.name
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.reference_interest_rate
     *
     * @return the value of platform.reference_interest_rate
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getReferenceInterestRate() {
        return referenceInterestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.reference_interest_rate
     *
     * @param referenceInterestRate the value for platform.reference_interest_rate
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setReferenceInterestRate(String referenceInterestRate) {
        this.referenceInterestRate = referenceInterestRate == null ? null : referenceInterestRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.reference_day
     *
     * @return the value of platform.reference_day
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getReferenceDay() {
        return referenceDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.reference_day
     *
     * @param referenceDay the value for platform.reference_day
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setReferenceDay(String referenceDay) {
        this.referenceDay = referenceDay == null ? null : referenceDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.loan_money_low
     *
     * @return the value of platform.loan_money_low
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getLoanMoneyLow() {
        return loanMoneyLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.loan_money_low
     *
     * @param loanMoneyLow the value for platform.loan_money_low
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setLoanMoneyLow(String loanMoneyLow) {
        this.loanMoneyLow = loanMoneyLow == null ? null : loanMoneyLow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.loan_money_high
     *
     * @return the value of platform.loan_money_high
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getLoanMoneyHigh() {
        return loanMoneyHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.loan_money_high
     *
     * @param loanMoneyHigh the value for platform.loan_money_high
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setLoanMoneyHigh(String loanMoneyHigh) {
        this.loanMoneyHigh = loanMoneyHigh == null ? null : loanMoneyHigh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.loan_cycle_low
     *
     * @return the value of platform.loan_cycle_low
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getLoanCycleLow() {
        return loanCycleLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.loan_cycle_low
     *
     * @param loanCycleLow the value for platform.loan_cycle_low
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setLoanCycleLow(String loanCycleLow) {
        this.loanCycleLow = loanCycleLow == null ? null : loanCycleLow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.loan_cycle_high
     *
     * @return the value of platform.loan_cycle_high
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getLoanCycleHigh() {
        return loanCycleHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.loan_cycle_high
     *
     * @param loanCycleHigh the value for platform.loan_cycle_high
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setLoanCycleHigh(String loanCycleHigh) {
        this.loanCycleHigh = loanCycleHigh == null ? null : loanCycleHigh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.fast_loan
     *
     * @return the value of platform.fast_loan
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getFastLoan() {
        return fastLoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.fast_loan
     *
     * @param fastLoan the value for platform.fast_loan
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setFastLoan(String fastLoan) {
        this.fastLoan = fastLoan == null ? null : fastLoan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.fast_loan_time
     *
     * @return the value of platform.fast_loan_time
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getFastLoanTime() {
        return fastLoanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.fast_loan_time
     *
     * @param fastLoanTime the value for platform.fast_loan_time
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setFastLoanTime(String fastLoanTime) {
        this.fastLoanTime = fastLoanTime == null ? null : fastLoanTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.idcard
     *
     * @return the value of platform.idcard
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.idcard
     *
     * @param idcard the value for platform.idcard
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.carrier_warrant
     *
     * @return the value of platform.carrier_warrant
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getCarrierWarrant() {
        return carrierWarrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.carrier_warrant
     *
     * @param carrierWarrant the value for platform.carrier_warrant
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setCarrierWarrant(String carrierWarrant) {
        this.carrierWarrant = carrierWarrant == null ? null : carrierWarrant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.bank_card
     *
     * @return the value of platform.bank_card
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.bank_card
     *
     * @param bankCard the value for platform.bank_card
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.zhima
     *
     * @return the value of platform.zhima
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getZhima() {
        return zhima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.zhima
     *
     * @param zhima the value for platform.zhima
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setZhima(String zhima) {
        this.zhima = zhima == null ? null : zhima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.xuexinwang
     *
     * @return the value of platform.xuexinwang
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getXuexinwang() {
        return xuexinwang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.xuexinwang
     *
     * @param xuexinwang the value for platform.xuexinwang
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setXuexinwang(String xuexinwang) {
        this.xuexinwang = xuexinwang == null ? null : xuexinwang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.taobao
     *
     * @return the value of platform.taobao
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getTaobao() {
        return taobao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.taobao
     *
     * @param taobao the value for platform.taobao
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setTaobao(String taobao) {
        this.taobao = taobao == null ? null : taobao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.zhifubao
     *
     * @return the value of platform.zhifubao
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getZhifubao() {
        return zhifubao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.zhifubao
     *
     * @param zhifubao the value for platform.zhifubao
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setZhifubao(String zhifubao) {
        this.zhifubao = zhifubao == null ? null : zhifubao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.qq
     *
     * @return the value of platform.qq
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.qq
     *
     * @param qq the value for platform.qq
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.applyconditions
     *
     * @return the value of platform.applyconditions
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getApplyconditions() {
        return applyconditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.applyconditions
     *
     * @param applyconditions the value for platform.applyconditions
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setApplyconditions(String applyconditions) {
        this.applyconditions = applyconditions == null ? null : applyconditions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.homepage
     *
     * @return the value of platform.homepage
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.homepage
     *
     * @param homepage the value for platform.homepage
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage == null ? null : homepage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.displayposition
     *
     * @return the value of platform.displayposition
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public Integer getDisplayposition() {
        return displayposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.displayposition
     *
     * @param displayposition the value for platform.displayposition
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setDisplayposition(Integer displayposition) {
        this.displayposition = displayposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.onshelves
     *
     * @return the value of platform.onshelves
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getOnshelves() {
        return onshelves;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.onshelves
     *
     * @param onshelves the value for platform.onshelves
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setOnshelves(String onshelves) {
        this.onshelves = onshelves == null ? null : onshelves.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.labelshow
     *
     * @return the value of platform.labelshow
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getLabelshow() {
        return labelshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.labelshow
     *
     * @param labelshow the value for platform.labelshow
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setLabelshow(String labelshow) {
        this.labelshow = labelshow == null ? null : labelshow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.image_url
     *
     * @return the value of platform.image_url
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.image_url
     *
     * @param imageUrl the value for platform.image_url
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.jumpurl
     *
     * @return the value of platform.jumpurl
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public String getJumpurl() {
        return jumpurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.jumpurl
     *
     * @param jumpurl the value for platform.jumpurl
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setJumpurl(String jumpurl) {
        this.jumpurl = jumpurl == null ? null : jumpurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.create_time
     *
     * @return the value of platform.create_time
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.create_time
     *
     * @param createTime the value for platform.create_time
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Platform other = (Platform) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getReferenceInterestRate() == null ? other.getReferenceInterestRate() == null : this.getReferenceInterestRate().equals(other.getReferenceInterestRate()))
                && (this.getReferenceDay() == null ? other.getReferenceDay() == null : this.getReferenceDay().equals(other.getReferenceDay()))
                && (this.getLoanMoneyLow() == null ? other.getLoanMoneyLow() == null : this.getLoanMoneyLow().equals(other.getLoanMoneyLow()))
                && (this.getLoanMoneyHigh() == null ? other.getLoanMoneyHigh() == null : this.getLoanMoneyHigh().equals(other.getLoanMoneyHigh()))
                && (this.getLoanCycleLow() == null ? other.getLoanCycleLow() == null : this.getLoanCycleLow().equals(other.getLoanCycleLow()))
                && (this.getLoanCycleHigh() == null ? other.getLoanCycleHigh() == null : this.getLoanCycleHigh().equals(other.getLoanCycleHigh()))
                && (this.getFastLoan() == null ? other.getFastLoan() == null : this.getFastLoan().equals(other.getFastLoan()))
                && (this.getFastLoanTime() == null ? other.getFastLoanTime() == null : this.getFastLoanTime().equals(other.getFastLoanTime()))
                && (this.getIdcard() == null ? other.getIdcard() == null : this.getIdcard().equals(other.getIdcard()))
                && (this.getCarrierWarrant() == null ? other.getCarrierWarrant() == null : this.getCarrierWarrant().equals(other.getCarrierWarrant()))
                && (this.getBankCard() == null ? other.getBankCard() == null : this.getBankCard().equals(other.getBankCard()))
                && (this.getZhima() == null ? other.getZhima() == null : this.getZhima().equals(other.getZhima()))
                && (this.getXuexinwang() == null ? other.getXuexinwang() == null : this.getXuexinwang().equals(other.getXuexinwang()))
                && (this.getTaobao() == null ? other.getTaobao() == null : this.getTaobao().equals(other.getTaobao()))
                && (this.getZhifubao() == null ? other.getZhifubao() == null : this.getZhifubao().equals(other.getZhifubao()))
                && (this.getQq() == null ? other.getQq() == null : this.getQq().equals(other.getQq()))
                && (this.getApplyconditions() == null ? other.getApplyconditions() == null : this.getApplyconditions().equals(other.getApplyconditions()))
                && (this.getHomepage() == null ? other.getHomepage() == null : this.getHomepage().equals(other.getHomepage()))
                && (this.getDisplayposition() == null ? other.getDisplayposition() == null : this.getDisplayposition().equals(other.getDisplayposition()))
                && (this.getOnshelves() == null ? other.getOnshelves() == null : this.getOnshelves().equals(other.getOnshelves()))
                && (this.getLabelshow() == null ? other.getLabelshow() == null : this.getLabelshow().equals(other.getLabelshow()))
                && (this.getImageUrl() == null ? other.getImageUrl() == null : this.getImageUrl().equals(other.getImageUrl()))
                && (this.getJumpurl() == null ? other.getJumpurl() == null : this.getJumpurl().equals(other.getJumpurl()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getReferenceInterestRate() == null) ? 0 : getReferenceInterestRate().hashCode());
        result = prime * result + ((getReferenceDay() == null) ? 0 : getReferenceDay().hashCode());
        result = prime * result + ((getLoanMoneyLow() == null) ? 0 : getLoanMoneyLow().hashCode());
        result = prime * result + ((getLoanMoneyHigh() == null) ? 0 : getLoanMoneyHigh().hashCode());
        result = prime * result + ((getLoanCycleLow() == null) ? 0 : getLoanCycleLow().hashCode());
        result = prime * result + ((getLoanCycleHigh() == null) ? 0 : getLoanCycleHigh().hashCode());
        result = prime * result + ((getFastLoan() == null) ? 0 : getFastLoan().hashCode());
        result = prime * result + ((getFastLoanTime() == null) ? 0 : getFastLoanTime().hashCode());
        result = prime * result + ((getIdcard() == null) ? 0 : getIdcard().hashCode());
        result = prime * result + ((getCarrierWarrant() == null) ? 0 : getCarrierWarrant().hashCode());
        result = prime * result + ((getBankCard() == null) ? 0 : getBankCard().hashCode());
        result = prime * result + ((getZhima() == null) ? 0 : getZhima().hashCode());
        result = prime * result + ((getXuexinwang() == null) ? 0 : getXuexinwang().hashCode());
        result = prime * result + ((getTaobao() == null) ? 0 : getTaobao().hashCode());
        result = prime * result + ((getZhifubao() == null) ? 0 : getZhifubao().hashCode());
        result = prime * result + ((getQq() == null) ? 0 : getQq().hashCode());
        result = prime * result + ((getApplyconditions() == null) ? 0 : getApplyconditions().hashCode());
        result = prime * result + ((getHomepage() == null) ? 0 : getHomepage().hashCode());
        result = prime * result + ((getDisplayposition() == null) ? 0 : getDisplayposition().hashCode());
        result = prime * result + ((getOnshelves() == null) ? 0 : getOnshelves().hashCode());
        result = prime * result + ((getLabelshow() == null) ? 0 : getLabelshow().hashCode());
        result = prime * result + ((getImageUrl() == null) ? 0 : getImageUrl().hashCode());
        result = prime * result + ((getJumpurl() == null) ? 0 : getJumpurl().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform
     *
     * @mbggenerated Fri Dec 08 17:55:10 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", referenceInterestRate=").append(referenceInterestRate);
        sb.append(", referenceDay=").append(referenceDay);
        sb.append(", loanMoneyLow=").append(loanMoneyLow);
        sb.append(", loanMoneyHigh=").append(loanMoneyHigh);
        sb.append(", loanCycleLow=").append(loanCycleLow);
        sb.append(", loanCycleHigh=").append(loanCycleHigh);
        sb.append(", fastLoan=").append(fastLoan);
        sb.append(", fastLoanTime=").append(fastLoanTime);
        sb.append(", idcard=").append(idcard);
        sb.append(", carrierWarrant=").append(carrierWarrant);
        sb.append(", bankCard=").append(bankCard);
        sb.append(", zhima=").append(zhima);
        sb.append(", xuexinwang=").append(xuexinwang);
        sb.append(", taobao=").append(taobao);
        sb.append(", zhifubao=").append(zhifubao);
        sb.append(", qq=").append(qq);
        sb.append(", applyconditions=").append(applyconditions);
        sb.append(", homepage=").append(homepage);
        sb.append(", displayposition=").append(displayposition);
        sb.append(", onshelves=").append(onshelves);
        sb.append(", labelshow=").append(labelshow);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", jumpurl=").append(jumpurl);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}