package com.fuhui.mybatis.generator.model;

import java.io.Serializable;

public class Role implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleid
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolestate
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Integer rolestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolename
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth1
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth2
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth3
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth4
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth5
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth6
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth7
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth8
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth9
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth10
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth11
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth12
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth13
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth14
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth15
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth16
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth17
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth18
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth19
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.auth20
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private Boolean auth20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleid
     *
     * @return the value of role.roleid
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleid
     *
     * @param roleid the value for role.roleid
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolestate
     *
     * @return the value of role.rolestate
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Integer getRolestate() {
        return rolestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolestate
     *
     * @param rolestate the value for role.rolestate
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setRolestate(Integer rolestate) {
        this.rolestate = rolestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolename
     *
     * @return the value of role.rolename
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolename
     *
     * @param rolename the value for role.rolename
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth1
     *
     * @return the value of role.auth1
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth1() {
        return auth1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth1
     *
     * @param auth1 the value for role.auth1
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth1(Boolean auth1) {
        this.auth1 = auth1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth2
     *
     * @return the value of role.auth2
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth2() {
        return auth2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth2
     *
     * @param auth2 the value for role.auth2
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth2(Boolean auth2) {
        this.auth2 = auth2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth3
     *
     * @return the value of role.auth3
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth3() {
        return auth3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth3
     *
     * @param auth3 the value for role.auth3
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth3(Boolean auth3) {
        this.auth3 = auth3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth4
     *
     * @return the value of role.auth4
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth4() {
        return auth4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth4
     *
     * @param auth4 the value for role.auth4
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth4(Boolean auth4) {
        this.auth4 = auth4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth5
     *
     * @return the value of role.auth5
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth5() {
        return auth5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth5
     *
     * @param auth5 the value for role.auth5
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth5(Boolean auth5) {
        this.auth5 = auth5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth6
     *
     * @return the value of role.auth6
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth6() {
        return auth6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth6
     *
     * @param auth6 the value for role.auth6
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth6(Boolean auth6) {
        this.auth6 = auth6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth7
     *
     * @return the value of role.auth7
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth7() {
        return auth7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth7
     *
     * @param auth7 the value for role.auth7
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth7(Boolean auth7) {
        this.auth7 = auth7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth8
     *
     * @return the value of role.auth8
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth8() {
        return auth8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth8
     *
     * @param auth8 the value for role.auth8
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth8(Boolean auth8) {
        this.auth8 = auth8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth9
     *
     * @return the value of role.auth9
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth9() {
        return auth9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth9
     *
     * @param auth9 the value for role.auth9
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth9(Boolean auth9) {
        this.auth9 = auth9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth10
     *
     * @return the value of role.auth10
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth10() {
        return auth10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth10
     *
     * @param auth10 the value for role.auth10
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth10(Boolean auth10) {
        this.auth10 = auth10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth11
     *
     * @return the value of role.auth11
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth11() {
        return auth11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth11
     *
     * @param auth11 the value for role.auth11
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth11(Boolean auth11) {
        this.auth11 = auth11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth12
     *
     * @return the value of role.auth12
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth12() {
        return auth12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth12
     *
     * @param auth12 the value for role.auth12
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth12(Boolean auth12) {
        this.auth12 = auth12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth13
     *
     * @return the value of role.auth13
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth13() {
        return auth13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth13
     *
     * @param auth13 the value for role.auth13
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth13(Boolean auth13) {
        this.auth13 = auth13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth14
     *
     * @return the value of role.auth14
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth14() {
        return auth14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth14
     *
     * @param auth14 the value for role.auth14
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth14(Boolean auth14) {
        this.auth14 = auth14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth15
     *
     * @return the value of role.auth15
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth15() {
        return auth15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth15
     *
     * @param auth15 the value for role.auth15
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth15(Boolean auth15) {
        this.auth15 = auth15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth16
     *
     * @return the value of role.auth16
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth16() {
        return auth16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth16
     *
     * @param auth16 the value for role.auth16
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth16(Boolean auth16) {
        this.auth16 = auth16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth17
     *
     * @return the value of role.auth17
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth17() {
        return auth17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth17
     *
     * @param auth17 the value for role.auth17
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth17(Boolean auth17) {
        this.auth17 = auth17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth18
     *
     * @return the value of role.auth18
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth18() {
        return auth18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth18
     *
     * @param auth18 the value for role.auth18
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth18(Boolean auth18) {
        this.auth18 = auth18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth19
     *
     * @return the value of role.auth19
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth19() {
        return auth19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth19
     *
     * @param auth19 the value for role.auth19
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth19(Boolean auth19) {
        this.auth19 = auth19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.auth20
     *
     * @return the value of role.auth20
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public Boolean getAuth20() {
        return auth20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.auth20
     *
     * @param auth20 the value for role.auth20
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    public void setAuth20(Boolean auth20) {
        this.auth20 = auth20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Role other = (Role) that;
        return (this.getRoleid() == null ? other.getRoleid() == null : this.getRoleid().equals(other.getRoleid()))
            && (this.getRolestate() == null ? other.getRolestate() == null : this.getRolestate().equals(other.getRolestate()))
            && (this.getRolename() == null ? other.getRolename() == null : this.getRolename().equals(other.getRolename()))
            && (this.getAuth1() == null ? other.getAuth1() == null : this.getAuth1().equals(other.getAuth1()))
            && (this.getAuth2() == null ? other.getAuth2() == null : this.getAuth2().equals(other.getAuth2()))
            && (this.getAuth3() == null ? other.getAuth3() == null : this.getAuth3().equals(other.getAuth3()))
            && (this.getAuth4() == null ? other.getAuth4() == null : this.getAuth4().equals(other.getAuth4()))
            && (this.getAuth5() == null ? other.getAuth5() == null : this.getAuth5().equals(other.getAuth5()))
            && (this.getAuth6() == null ? other.getAuth6() == null : this.getAuth6().equals(other.getAuth6()))
            && (this.getAuth7() == null ? other.getAuth7() == null : this.getAuth7().equals(other.getAuth7()))
            && (this.getAuth8() == null ? other.getAuth8() == null : this.getAuth8().equals(other.getAuth8()))
            && (this.getAuth9() == null ? other.getAuth9() == null : this.getAuth9().equals(other.getAuth9()))
            && (this.getAuth10() == null ? other.getAuth10() == null : this.getAuth10().equals(other.getAuth10()))
            && (this.getAuth11() == null ? other.getAuth11() == null : this.getAuth11().equals(other.getAuth11()))
            && (this.getAuth12() == null ? other.getAuth12() == null : this.getAuth12().equals(other.getAuth12()))
            && (this.getAuth13() == null ? other.getAuth13() == null : this.getAuth13().equals(other.getAuth13()))
            && (this.getAuth14() == null ? other.getAuth14() == null : this.getAuth14().equals(other.getAuth14()))
            && (this.getAuth15() == null ? other.getAuth15() == null : this.getAuth15().equals(other.getAuth15()))
            && (this.getAuth16() == null ? other.getAuth16() == null : this.getAuth16().equals(other.getAuth16()))
            && (this.getAuth17() == null ? other.getAuth17() == null : this.getAuth17().equals(other.getAuth17()))
            && (this.getAuth18() == null ? other.getAuth18() == null : this.getAuth18().equals(other.getAuth18()))
            && (this.getAuth19() == null ? other.getAuth19() == null : this.getAuth19().equals(other.getAuth19()))
            && (this.getAuth20() == null ? other.getAuth20() == null : this.getAuth20().equals(other.getAuth20()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleid() == null) ? 0 : getRoleid().hashCode());
        result = prime * result + ((getRolestate() == null) ? 0 : getRolestate().hashCode());
        result = prime * result + ((getRolename() == null) ? 0 : getRolename().hashCode());
        result = prime * result + ((getAuth1() == null) ? 0 : getAuth1().hashCode());
        result = prime * result + ((getAuth2() == null) ? 0 : getAuth2().hashCode());
        result = prime * result + ((getAuth3() == null) ? 0 : getAuth3().hashCode());
        result = prime * result + ((getAuth4() == null) ? 0 : getAuth4().hashCode());
        result = prime * result + ((getAuth5() == null) ? 0 : getAuth5().hashCode());
        result = prime * result + ((getAuth6() == null) ? 0 : getAuth6().hashCode());
        result = prime * result + ((getAuth7() == null) ? 0 : getAuth7().hashCode());
        result = prime * result + ((getAuth8() == null) ? 0 : getAuth8().hashCode());
        result = prime * result + ((getAuth9() == null) ? 0 : getAuth9().hashCode());
        result = prime * result + ((getAuth10() == null) ? 0 : getAuth10().hashCode());
        result = prime * result + ((getAuth11() == null) ? 0 : getAuth11().hashCode());
        result = prime * result + ((getAuth12() == null) ? 0 : getAuth12().hashCode());
        result = prime * result + ((getAuth13() == null) ? 0 : getAuth13().hashCode());
        result = prime * result + ((getAuth14() == null) ? 0 : getAuth14().hashCode());
        result = prime * result + ((getAuth15() == null) ? 0 : getAuth15().hashCode());
        result = prime * result + ((getAuth16() == null) ? 0 : getAuth16().hashCode());
        result = prime * result + ((getAuth17() == null) ? 0 : getAuth17().hashCode());
        result = prime * result + ((getAuth18() == null) ? 0 : getAuth18().hashCode());
        result = prime * result + ((getAuth19() == null) ? 0 : getAuth19().hashCode());
        result = prime * result + ((getAuth20() == null) ? 0 : getAuth20().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Sun Dec 03 19:53:52 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", rolestate=").append(rolestate);
        sb.append(", rolename=").append(rolename);
        sb.append(", auth1=").append(auth1);
        sb.append(", auth2=").append(auth2);
        sb.append(", auth3=").append(auth3);
        sb.append(", auth4=").append(auth4);
        sb.append(", auth5=").append(auth5);
        sb.append(", auth6=").append(auth6);
        sb.append(", auth7=").append(auth7);
        sb.append(", auth8=").append(auth8);
        sb.append(", auth9=").append(auth9);
        sb.append(", auth10=").append(auth10);
        sb.append(", auth11=").append(auth11);
        sb.append(", auth12=").append(auth12);
        sb.append(", auth13=").append(auth13);
        sb.append(", auth14=").append(auth14);
        sb.append(", auth15=").append(auth15);
        sb.append(", auth16=").append(auth16);
        sb.append(", auth17=").append(auth17);
        sb.append(", auth18=").append(auth18);
        sb.append(", auth19=").append(auth19);
        sb.append(", auth20=").append(auth20);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}