package com.fuhui.mybatis.generator.dao;

import com.fuhui.common.entity.QueryCondition;
import com.fuhui.mybatis.generator.model.FhUser;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FhUserMapper {

    /**
     * 获取用户的列表
     * @param queryCondition
     * @return
     */
    List<FhUser> selectFhUserList(QueryCondition queryCondition);

    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_user
     *
     * @mbggenerated Sat Dec 02 16:50:41 CST 2017
     */
    int insert(FhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_user
     *
     * @mbggenerated Sat Dec 02 16:50:41 CST 2017
     */
    int insertSelective(FhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_user
     *
     * @mbggenerated Sat Dec 02 16:50:41 CST 2017
     */
    FhUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_user
     *
     * @mbggenerated Sat Dec 02 16:50:41 CST 2017
     */
    int updateByPrimaryKeySelective(FhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fh_user
     *
     * @mbggenerated Sat Dec 02 16:50:41 CST 2017
     */
    int updateByPrimaryKey(FhUser record);


    FhUser selectByMobile(String mobile);
}